local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 7.0
  rolling_window: true
  width: 2.5 
  height: 2.5
  resolution: 0.05
  transform_tolerance: 0.5
  cost_scaling_factor: 5
  inflation_radius: 0.55

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
